# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Laboon < Formula
  desc ""
  homepage "https://github.com/arisnacg/laboon"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arisnacg/laboon/releases/download/v0.1.0/laboon_Darwin_arm64.tar.gz"
      sha256 "9adffeb69a2757f0e51ef19ced8cc594eb92b0b83a586ca9f36bcc6f22451298"

      def install
        bin.install "laboon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arisnacg/laboon/releases/download/v0.1.0/laboon_Darwin_x86_64.tar.gz"
      sha256 "640f56b216a0664604f288efa11283242049b9c0c98321fd00e830e739c4bee0"

      def install
        bin.install "laboon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arisnacg/laboon/releases/download/v0.1.0/laboon_Linux_arm64.tar.gz"
      sha256 "3b40de8676a678223efdf51d06699f6922302b402c3aa436b3e13d122de76ff0"

      def install
        bin.install "laboon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arisnacg/laboon/releases/download/v0.1.0/laboon_Linux_x86_64.tar.gz"
      sha256 "5149b8465a450d7fe8dcc031a3609beb62412a253016d47265bfb7dda1d68b79"

      def install
        bin.install "laboon"
      end
    end
  end
end
